# permissions for end users to edit configs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tanuu-operator
    app.kubernetes.io/managed-by: kustomize
  name: config-editor-role
rules:
- apiGroups:
  - tanuu.dev
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tanuu.dev
  resources:
  - configs/status
  verbs:
  - get
