# permissions for end users to edit devenvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tanuu-operator
    app.kubernetes.io/managed-by: kustomize
  name: devenv-editor-role
rules:
- apiGroups:
  - tanuu.dev
  resources:
  - devenvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tanuu.dev
  resources:
  - devenvs/status
  verbs:
  - get
