apiVersion: tanuu.dev/v1alpha1
kind: Devenv
metadata:
  labels:
    app.kubernetes.io/name: tanuu-operator
    app.kubernetes.io/managed-by: kustomize
  name: devenv-sample
spec:
  name: "example-dev-environment"
  cloudProvider: "google"
  workerReplicas: 2
  ctrlReplicas: 1
  gpuReplicas: 0
  zone: "europe-west4-a"
  # The following fields are optional
  workerSelector: "worker"
  ctrlSelector: "controller"
  gpuSelector: "gpu"
  
