apiVersion: tanuu.dev/v1alpha1
kind: Devenv
metadata:
  labels:
    app.kubernetes.io/name: tanuu-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo-platform-workshop
spec:
  name: "platform-workshop"
  cloudProvider: "google"
  workerReplicas: 2
  ctrlReplicas: 1
  gpuReplicas: 0
  k8sVersion: "v1.29.4"
  talosVersion: "v1.7.6"
  zone: "europe-north1-c"
  # The following fields are optional
  workerSelector: "base-176"
  ctrlSelector: "base-176"
  gpuSelector: "gpu-176"
  
